require conf/machine/apalis-imx8.conf

MACHINE_NAME = "Apalis-iMX8-refeyn"
UBOOT_CONFIG[sd] = "apalis-imx8-refeyn_defconfig,sdcard"

KERNEL_DEVICETREE += " \
    ${KERNEL_DTB_PREFIX}imx8qm-apalis-v1.1-generic-carrier-generic-aux.dtb \
    ${KERNEL_DTB_PREFIX}imx8qm-apalis-v1.1-tdx-ixora-13-generic-aux.dtb \
    ${KERNEL_DTB_PREFIX}imx8qm-apalis-v1.1-ec-asm-00037-01-generic-aux.dtb \
    ${KERNEL_DTB_PREFIX}imx8qm-apalis-v1.1-ec-asm-00037-01-ec-asm-00027-02.dtb \
    ${KERNEL_DTB_PREFIX}imx8qm-apalis-v1.1-ec-asm-00037-02-generic-aux.dtb \
    ${KERNEL_DTB_PREFIX}imx8qm-apalis-v1.1-ec-asm-00037-02-ec-asm-00027-02.dtb \
"
TEZI_EXTERNAL_KERNEL_DEVICETREE_BOOT = ""
