require conf/machine/aquila-am69.conf

MACHINE_NAME = "Aquila-AM69-refeyn"
MACHINEOVERRIDES =. "aquila-am69:"
UBOOT_CONFIG[sd] = "aquila-am69_a72_refeyn_defconfig,sdcard"

KERNEL_DEVICETREE += " \
    ${KERNEL_DTB_PREFIX}k3-am69-aquila-v1.0-tdx-dev-12-generic-aux.dtb \
    ${KERNEL_DTB_PREFIX}k3-am69-aquila-v1.0-generic-carrier-generic-aux.dtb \
    ${KERNEL_DTB_PREFIX}k3-am69-aquila-v1.0-ec-asm-00044-03-generic-aux.dtb \
    ${KERNEL_DTB_PREFIX}k3-am69-aquila-v1.0-ec-asm-00044-03-ec-asm-00048-02.dtb \
    ${KERNEL_DTB_PREFIX}k3-am69-aquila-v1.1-tdx-dev-12-generic-aux.dtb \
    ${KERNEL_DTB_PREFIX}k3-am69-aquila-v1.1-generic-carrier-generic-aux.dtb \
    ${KERNEL_DTB_PREFIX}k3-am69-aquila-v1.1-ec-asm-00044-03-generic-aux.dtb \
    ${KERNEL_DTB_PREFIX}k3-am69-aquila-v1.1-ec-asm-00044-03-ec-asm-00048-02.dtb \
"
TEZI_EXTERNAL_KERNEL_DEVICETREE_BOOT = ""
KERNEL_IMAGETYPE = "fitImage"
IMAGE_BOOT_FILES_REMOVE:append = " boot.scr-${MACHINE};boot.scr overlays.txt overlays/*;overlays/*"
