[Transfer]
ProtectVersion=%A
Verify=no

[Source]
Type=regular-file
Path=/tmp/update/
MatchPattern=rootfs_@v.ext4.xz

[Target]
Type=partition
Path=auto
MatchPattern=rootfs_@v
MatchPartitionType=root
InstancesMax=2
