[Transfer]
ProtectVersion=%A
Verify=no

[Source]
Type=regular-file
Path=/tmp/update/
MatchPattern=fitImage_@v

[Target]
Type=regular-file
Path=/boot/
MatchPattern=fitImage_@v+@l-@d fitImage_@v+@l fitImage_@v
Mode=0444
TriesLeft=3
TriesDone=0
InstancesMax=2
