require conf/distro/tdx-xwayland.conf

DISTRO = "refeyn-wayland"
DISTRO_NAME = "Refeyn TDX Distro"

# Don't want XWayland
DISTRO_FEATURES:remove = " x11"
DISTRO_FEATURES:remove = " nfs"

# Disable patch status checking
ERROR_QA:remove = "patch-status"

# Do not commit build history
BUILDHISTORY_COMMIT = "0"

# Use a persistent log on the device
VOLATILE_LOG_DIR = "no"


IMAGE_VERSION = "2026.1.0-dev${DATETIME}"
IMAGE_VERSION[vardepsexclude] = "DATETIME"
