require conf/distro/torizon.conf

DISTRO = "refeyn-wayland"
DISTRO_NAME = "Refeyn TDX Distro"

# Don't want XWayland
DISTRO_FEATURES:remove = " x11"

# Disable patch status checking
ERROR_QA:remove = "patch-status"

# Do not commit build history
BUILDHISTORY_COMMIT = "0"

# Use a persistent log on the device
VOLATILE_LOG_DIR = "no"

# INCOMPATIBLE_LICENSE += "GPL-3.0-only GPL-3.0-or-later LGPL-3.0-only LGPL-3.0-or-later"
# INCOMPATIBLE_LICENSE_EXCEPTIONS += "nano:GPL-3.0-only"

USERADD_UID_TABLES = "files/refeyn-static-passwd"
USERADD_GID_TABLES = "files/refeyn-static-group"
