require conf/distro/tdx-xwayland.conf

DISTRO = "refeyn-wayland"
DISTRO_NAME = "Refeyn TDX Distro"

# Don't want XWayland
DISTRO_FEATURES:remove = " x11"
DISTRO_FEATURES:remove = " nfs"

# Disable patch status checking
ERROR_QA:remove = "patch-status"

# Do not commit build history
BUILDHISTORY_COMMIT = "0"

# Use a persistent log on the device
VOLATILE_LOG_DIR = "no"

DISTRO_FEATURES:append = " overlayfs"
DISTRO_FEATURES:remove = " bluetooth"
DISTRO_FEATURES:remove = " wifi"
DISTRO_FEATURES:remove = " 3g"
DISTRO_FEATURES:remove = " zeroconf"

DISTRO_VERSION = "26.1.0-dev${DATETIME}"
DISTRO_VERSION[vardepsexclude] = "DATETIME"

INHERIT += "cve-check"
include cve-extra-exclusions.inc
