name: Image build

on:
 workflow_dispatch:
 push:
  tags:
    - '*'
 schedule:
    - cron: '0 0 * * *'

jobs:
  deploy:
    name: Test and Deploy
    runs-on: yocto
    timeout-minutes: 500

    steps:
      - name: Clean build directory
        run: |
          rm -rf imx-refeyn
          mkdir imx-refeyn

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: imx-refeyn/meta-refeyn

      - name: Build
        run: |
          cd imx-refeyn

          # https://stackoverflow.com/a/57229018
          echo -e "[url \"https://api:${{secrets.REFEYN_CI_TOKEN}}@github.com/\"]\n\tinsteadOf = https://github.com/" >> .gitconfig
          echo -e "[url \"https://ssh:${{secrets.REFEYN_CI_TOKEN}}@github.com/\"]\n\tinsteadOf = ssh://git@github.com/" >> .gitconfig
          echo -e "[url \"https://git:${{secrets.REFEYN_CI_TOKEN}}@github.com/\"]\n\tinsteadOf = git@github.com:" >> .gitconfig

          export GITCONFIG_FILE=".gitconfig"
          kas build meta-refeyn/kas-project.yml
