name: Image build

on:
 workflow_dispatch:
 push:
  tags:
    - '*'
 schedule:
    - cron: '0 0 * * *'

jobs:
  deploy:
    name: Test and Deploy
    runs-on: yocto
    timeout-minutes: 500

    steps:
      - name: Clean build directory
        run: |
          mkdir -p imx-refeyn
          rm -rf imx-refeyn/build

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: imx-refeyn/meta-refeyn

      - name: Build
        run: |
          cd imx-refeyn

          # https://stackoverflow.com/a/57229018
          echo -e "[url \"https://api:${{secrets.REFEYN_CI_TOKEN}}@github.com/\"]\n\tinsteadOf = https://github.com/" >> .gitconfig
          echo -e "[url \"https://ssh:${{secrets.REFEYN_CI_TOKEN}}@github.com/\"]\n\tinsteadOf = ssh://git@github.com/" >> .gitconfig
          echo -e "[url \"https://git:${{secrets.REFEYN_CI_TOKEN}}@github.com/\"]\n\tinsteadOf = git@github.com:" >> .gitconfig

          export GITCONFIG_FILE=".gitconfig"
          kas build meta-refeyn/kas-project.yml

      - uses: actions/upload-artifact@v4
        with:
          name: full-image-imx-image-refeyn-imx8qm-ec-asm-00014-01
          path: |
            imx-refeyn/build/tmp/deploy/images/imx8qm-ec-asm-00014-01/imx-boot-imx8qm-ec-asm-00014-01-sd.bin-flash_spl
            imx-refeyn/build/tmp/deploy/images/imx8qm-ec-asm-00014-01/imx-image-refeyn-imx8qm-ec-asm-00014-01.wic.*

      - uses: actions/upload-artifact@v4
        with:
          name: lite-image-imx-image-refeyn-imx8qm-ec-asm-00014-01
          path: |
            imx-refeyn/build/tmp/deploy/images/imx8qm-ec-asm-00014-01/imx-boot-imx8qm-ec-asm-00014-01-sd.bin-flash_spl
            imx-refeyn/build/tmp/deploy/images/imx8qm-ec-asm-00014-01/imx-image-refeyn-lite-imx8qm-ec-asm-00014-01.wic.*

      - uses: actions/upload-artifact@v4
        with:
          name: fat-image-imx-image-refeyn-imx8qm-ec-asm-00014-01
          path: |
            imx-refeyn/build/tmp/deploy/images/imx8qm-ec-asm-00014-01/imx-boot-imx8qm-ec-asm-00014-01-sd.bin-flash_spl
            imx-refeyn/build/tmp/deploy/images/imx8qm-ec-asm-00014-01/imx-image-refeyn-fat-imx8qm-ec-asm-00014-01.wic.*

      - uses: actions/upload-artifact@v4
        with:
          name: boot-files-imx-image-refeyn-imx8qm-ec-asm-00014-01
          path: |
            imx-refeyn/build/tmp/deploy/images/imx8qm-ec-asm-00014-01/imx-boot-imx8qm-ec-asm-00014-01-sd.bin-flash_spl
            imx-refeyn/build/tmp/deploy/images/imx8qm-ec-asm-00014-01/imx8qm-ec-asm-00014-01-with-ec-asm-{00025-02,00027-01}.dtb

      - name: Cleanup
        if: always()
        run: rm imx-refeyn/.gitconfig
