name: Image build

on:
 workflow_dispatch:
  inputs:
    no_cythonize:
      description: "Skip cythonization"
      type: boolean
      default: false
      required: false
    lw8_ref:
      description: "lw8 branch, commit or tag"
      type: string
      default: "release/26.1.0"
      required: false
 push:
  tags:
    - '*'
 schedule:
    - cron: '0 0 * * *'

jobs:
  deploy:
    name: Test and Deploy
    runs-on: yocto
    timeout-minutes: 500

    env:
      REFEYN_NO_CYTHONIZE: ${{ inputs.no_cythonize && '1' || '0' }}

    steps:
      - name: Clean build directory
        run: |
          mkdir -p toradex-refeyn
          rm -rf toradex-refeyn/build

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: toradex-refeyn/meta-refeyn

      - name: Build
        run: |
          cd toradex-refeyn

          set -o allexport
          source <(python meta-refeyn/resolve_commits.py ${{secrets.REFEYN_CI_TOKEN}} ${{ inputs.lw8_ref || 'release/26.1.0' }})
          set +o allexport

          env | grep REFEYN_

          # https://stackoverflow.com/a/57229018
          echo -e "[url \"https://api:${{secrets.REFEYN_CI_TOKEN}}@github.com/\"]\n\tinsteadOf = https://github.com/" >> .gitconfig
          echo -e "[url \"https://ssh:${{secrets.REFEYN_CI_TOKEN}}@github.com/\"]\n\tinsteadOf = ssh://git@github.com/" >> .gitconfig
          echo -e "[url \"https://git:${{secrets.REFEYN_CI_TOKEN}}@github.com/\"]\n\tinsteadOf = git@github.com:" >> .gitconfig

          export GITCONFIG_FILE=".gitconfig"
          kas build meta-refeyn/kas-project.yml

      - name: Upload Aquila-AM69-Refeyn-Lite-Image
        id: lite-tezi-image-upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: |
            toradex-refeyn/build/deploy-ti/images/aquila-am69-refeyn/Aquila-AM69-refeyn_Refeyn-Lite-Image-Tezi_*.tar

      - name: Upload Aquila-AM69-Refeyn-Image
        id: tezi-image-upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: |
            toradex-refeyn/build/deploy-ti/images/aquila-am69-refeyn/Aquila-AM69-refeyn_Refeyn-Image-Tezi_*.tar

      - name: Upload Aquila-AM69-Refeyn-Fat-Image
        id: fat-tezi-image-upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: |
            toradex-refeyn/build/deploy-ti/images/aquila-am69-refeyn/Aquila-AM69-refeyn_Refeyn-Fat-Image-Tezi_*.tar

      - name: Upload Aquila-AM69-Refeyn-Lite-Update
        id: lite-sysupdate-image-upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: |
            toradex-refeyn/build/deploy-ti/images/aquila-am69-refeyn/Aquila-AM69-refeyn_Refeyn-Lite-Image-*-sysupdate.tar

      - name: Upload Aquila-AM69-Refeyn-Update
        id: sysupdate-image-upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: |
            toradex-refeyn/build/deploy-ti/images/aquila-am69-refeyn/Aquila-AM69-refeyn_Refeyn-Image-*-sysupdate.tar

      - name: Upload Aquila-AM69-Refeyn-Fat-Update
        id: fat-sysupdate-image-upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: |
            toradex-refeyn/build/deploy-ti/images/aquila-am69-refeyn/Aquila-AM69-refeyn_Refeyn-Fat-Image-*-sysupdate.tar

      - name: Upload Aquila-AM69-Refeyn-Image-Licences
        id: licences-upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: |
            toradex-refeyn/build/tmp/deploy/licenses/aquila_am69_refeyn/Aquila-AM69-refeyn_Refeyn-Image/license.manifest

      - name: Clone dev_utils
        uses: actions/checkout@v4
        with:
          repository: 'refeyn/dev_utils'
          token: ${{secrets.REFEYN_CI_TOKEN}}
          path: dev_utils

      - name: Build dev_utils venv
        run: |
          cd dev_utils
          python setup_deploy.py

      - name: Parse and upload coverage
        env:
          DEV_UTILS_INTERNAL_PORTAL_API_KEY: ${{secrets.DEV_UTILS_INTERNAL_PORTAL_API_KEY}}
        run: |
          fakesha="$(echo toradex-refeyn/build/deploy-ti/images/aquila-am69-refeyn/Aquila-AM69-refeyn_Refeyn-Image-*-sysupdate.tar | grep "\d{14}" -oP)"
          cd dev_utils
          . activate_deploy.sh
          dev_utils portal upload-code-statistics ${{ github.event.repository.name }} $fakesha \
            --commit-timestamp $(date -Iseconds) \
            --build-url ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \
            --artefact-url "Tezi image" "MyMass" ${{ steps.tezi-image-upload.outputs.artifact-url }} \
            --artefact-url "Debugging Tezi image" "MyMass" ${{ steps.fat-tezi-image-upload.outputs.artifact-url }} \
            --artefact-url "SW update" "MyMass" ${{ steps.sysupdate-image-upload.outputs.artifact-url }} \
            --artefact-url "Debugging SW update" "MyMass" ${{ steps.fat-sysupdate-image-upload.outputs.artifact-url }} \
            --artefact-url "Package licence manifest" "MyMass" ${{ steps.licences-upload.outputs.artifact-url }} \
            ${{ github.event_name == 'schedule' && '--mark-on-master' || '' }} \

      - name: Cleanup
        if: always()
        run: |
          rm toradex-refeyn/.gitconfig
          find $DL_DIR -type f -atime +10 -delete
          find $SSTATE_DIR -type f -atime +10 -delete
